### ISSUE TITLE
Does not seem to work with command options

### ISSUE THREAD

**Issue by evanjamesjackson** [TorqIT/pimcore-command-locker-bundle#1]
Just gave this a try:
`bin/console torq:command-locker pimcore:deployment:classes-rebuild -c -d -n`
And received the following error:
```
The "-c" option does not exist.                                    
torq:command-locker <command-with-options>
```
Does the command I'm supplying need to be wrapped in something (e.g. quotes) if it has arguments of its own?

**Comment by lukemacausland** [comment]
@evanjamesjackson - you should be able to run the command like this: `bin/console torq:command-locker 'pimcore:deployment:classes-rebuild -c -d -n'`

![image](https://user-images.githubusercontent.com/58705994/158478016-452efdf4-5976-45f6-8228-4b3c4c405636.png)

I will update the documentation to include this for future users.

**Comment by lukemacausland** [comment]
Readme updated, to include quotes around the command name.
